#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# This is a one-shot fixup for source generated by the first rotation-v2 patch.
# It remains temporary and is removed before the PR is merged.

classic_path = ROOT / "src/classic.cpp"
classic = classic_path.read_text()
prototype = '''\nstatic void spr_child_rot(uint8_t sprite, int x, int y, int dx, int dy,\n                          uint8_t rotation, bool flip_x = false, bool flip_y = false);\nstatic void draw_rotated_2x2(uint8_t a, uint8_t b, uint8_t c, uint8_t d,\n                             int x, int y, uint8_t rotation);\n'''
marker = 'constexpr int TOTAL_STRAWBERRIES = 18;\n'
if prototype not in classic:
    if marker not in classic:
        raise SystemExit('classic.cpp prototype insertion marker missing')
    classic = classic.replace(marker, marker + prototype, 1)

# Default arguments belong on the forward declaration, not the later definition.
classic = classic.replace(
'''static void spr_child_rot(uint8_t sprite, int x, int y, int dx, int dy,
                          uint8_t rotation, bool flip_x = false, bool flip_y = false) {''',
'''static void spr_child_rot(uint8_t sprite, int x, int y, int dx, int dy,
                          uint8_t rotation, bool flip_x, bool flip_y) {''', 1)
classic_path.write_text(classic)

editor_path = ROOT / "tools/calculator-editor/src/main.cpp"
editor = editor_path.read_text()
old = '''    if(pressed(3,kb_Window)){
      EditRoom &r=project.rooms[room_index];const uint8_t index=cursor_y*16+cursor_x;
      uint8_t here=r.tiles[index],rot=rotate_id(here);
      if(here&&rot!=here){record_change(index,here,rot);r.tiles[index]=rot;set_notice("PIECE ROTATED");}
      else {uint8_t sel=PALETTE[palette_index],next=rotate_id(sel);int pi=palette_index_for(next);if(next!=sel&&pi>=0){palette_index=static_cast<uint8_t>(pi);set_notice("PALETTE ROTATED");}else set_notice("NO ROTATION");}
    }
'''
new = '''    if(pressed(3,kb_Window)){
      EditRoom &r=project.rooms[room_index];const uint8_t index=cursor_y*16+cursor_x;
      if(r.tiles[index]){
        const uint8_t before=r.rotations[index],after=static_cast<uint8_t>((before+1)&3);
        record_change(index,r.tiles[index],r.tiles[index],before,after);r.rotations[index]=after;
        set_notice(after==0?"PIECE ROTATION 0":after==1?"PIECE ROTATION 90":after==2?"PIECE ROTATION 180":"PIECE ROTATION 270");
      }else{
        placement_rotation=static_cast<uint8_t>((placement_rotation+1)&3);
        set_notice(placement_rotation==0?"PALETTE ROTATION 0":placement_rotation==1?"PALETTE ROTATION 90":placement_rotation==2?"PALETTE ROTATION 180":"PALETTE ROTATION 270");
      }
    }
'''
if old in editor:
    editor = editor.replace(old, new, 1)
elif 'rotate_id(' in editor:
    raise SystemExit('CELEDIT still contains rotate_id but expected WINDOW block was not found')

# Erasing should clear both the tile and its rotation, regardless of palette rotation.
editor = editor.replace('  paint(0);\n}\nvoid undo()', '  paint_cell(cursor_x,cursor_y,0,0);\n}\nvoid undo()', 1)
editor_path.write_text(editor)

print('Rotation v2 fixups applied.')
