NAME = CELEDIT
DESCRIPTION = "CEleste Level Editor"
COMPRESSED = YES
ARCHIVED = YES
CFLAGS = -Wall -Wextra -Oz -I../../src/gfx
CXXFLAGS = -Wall -Wextra -Oz -I../../src -I../../src/gfx
include $(shell cedev-config --makefile)
